[package]
name = "merak-strategy-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
schemars = "1.1.0"
serde = {version = "1.0.228",  features = ["derive"] }
serde_json = "1.0.145"
wit-bindgen = "0.51.0"